import localFont from "next/font/local";
import "./globals.css";
import Sidebar from "./components/sidebar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="flex h-screen w-full">
          {/* Sidebar */}
          <div className="flex-shrink-0 w-64"> {/* Ajusta el ancho a 64px en lugar de un tercio del viewport */}
            <Sidebar />
          </div>
          {/* Main content */}
          <div className="flex-grow bg-gray-100 p-8"> {/* Añade un fondo para diferenciar el contenido */}
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
